---
# tasks file for roles/apache
- name: install apache
  yum:
     name: httpd
     state: present
#- name: copy config files

#Copy index file to destination server
#  copy:
#     src: index.html
#     dest: /var/www/html/   
#import_tasks: install_htpd.yml

#Insert dynamic content
#  copy:
#   dest: /var/www/html/index.html
#   content:  "Hi this is from the host {{ansible_hostname}} and running the kernel {{ansible_kernel}} \n"
#  notify: restart apache
#

#Use Jinja2 template 
- name: Copy template to destination
  template:
    src: index1.html.j2
    dest: /var/www/html/index1.html
  notify: restart apache
