---
# tasks file for apache_config
# copy template vhost.conf file to apache config location
 - name: copy config file
   template:
     src: vhosts.conf.j2
     dest: /etc/httpd/conf.d/vhosts.conf
   notify: restart apache

 - name: create document root
   file:
     path: /var/www/html/{{item}}
     state: directory
   with_items:
     - vaishakh
     - neutron

 - name: Copy neutron conf file
   template:
      src: neutron.html.j2
      dest: /var/www/html/neutron/

 - name: Copy vaishakh conf file
   template:
      src: vaishakh.html.j2
      dest: /var/www/html/vaishakh/
 
